neo4j:
  image: neo4j:latest
  container_name: testneo4j
  environment:
  - NEO4J_AUTH=none
  ports:
  - "7474:7474"
  - "7687:7687"
  volumes:
  - $HOME/neo4j/data:/data
  - $HOME/neo4j/logs:/logs
  - $HOME/neo4j/import:/var/lib/neo4j/import
  - $HOME/neo4j/plugins:/plugins
  - $HOME/neo4j/conf:/conf